#!/bin/bash
git config status.showuntrackedfiles no
git clone git@github.com:rupa/z.git ~/z 2>/dev/null && echo -e "\033[0;32mz cloned\033[0m" || echo "z already cloned"

ln .vimwjm ~/.vimwjm
ln .bashwjm ~/.bashwjm
grep "source ~/.bashwjm" ~/.bashrc >/dev/null || echo "source ~/.bashwjm" >> ~/.bashrc
grep "so ~/.vimwjm" ~/.vimrc >/dev/null 2>/dev/null || echo "source ~/.vimwjm" >> ~/.vimrc

source ~/.bashrc
